PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS library_guides (
 id TEXT PRIMARY KEY NOT NULL, slug TEXT NOT NULL UNIQUE, crop_id TEXT NOT NULL,
 category TEXT NOT NULL CHECK(category IN ('crop','disease','deficiency','pest','practice','guide')),
 title_fr TEXT NOT NULL, title_en TEXT NOT NULL, title_pcm TEXT NOT NULL,
 summary_fr TEXT NOT NULL, summary_en TEXT NOT NULL, summary_pcm TEXT NOT NULL,
 reading_minutes INTEGER NOT NULL DEFAULT 4, image_key TEXT, featured INTEGER NOT NULL DEFAULT 0,
 recommended INTEGER NOT NULL DEFAULT 0, content_json TEXT NOT NULL DEFAULT '{}',
 installed INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_library_guides_filter ON library_guides(crop_id,category,installed,display_order);
CREATE TABLE IF NOT EXISTS library_bookmarks (guide_id TEXT PRIMARY KEY NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(guide_id) REFERENCES library_guides(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS library_reading_progress (guide_id TEXT PRIMARY KEY NOT NULL,progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100),updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(guide_id) REFERENCES library_guides(id) ON DELETE CASCADE);

INSERT OR IGNORE INTO library_guides (id,slug,crop_id,category,title_fr,title_en,title_pcm,summary_fr,summary_en,summary_pcm,reading_minutes,image_key,featured,recommended,content_json,installed,display_order) VALUES
('guide-01','potassium-maize','maize','deficiency','Carence en potassium du maïs','Potassium deficiency in maize','Potassium deficiency in maize','Fiche illustrée pour reconnaître, prévenir et gérer : carence en potassium du maïs.','Illustrated guide to recognize, prevent and manage potassium deficiency in maize.','Picture guide for know, prevent and manage potassium deficiency in maize.',6,'crop-maize',1,1,'{"symptoms":["Jaunissement des bords","Dessèchement marginal","Feuilles basses touchées en premier","Croissance parfois ralentie"],"confusions":["Stress hydrique","Carence en azote","Brûlure causée par un produit"],"actions":["Vérifier l’humidité du sol","Comparer plusieurs plants","Demander une analyse du sol si possible"],"prevention":["Fertiliser selon les besoins du sol","Maintenir la matière organique","Surveiller les feuilles âgées"]}',1,1),
('guide-02','nitrogen-maize','maize','deficiency','Carence en azote du maïs','Nitrogen deficiency in maize','Nitrogen deficiency in maize','Fiche illustrée pour reconnaître, prévenir et gérer : carence en azote du maïs.','Illustrated guide to recognize, prevent and manage nitrogen deficiency in maize.','Picture guide for know, prevent and manage nitrogen deficiency in maize.',4,'crop-maize',1,0,'{"symptoms":["Carence en azote du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,2),
('guide-03','phosphorus-maize','maize','deficiency','Carence en phosphore du maïs','Phosphorus deficiency in maize','Phosphorus deficiency in maize','Fiche illustrée pour reconnaître, prévenir et gérer : carence en phosphore du maïs.','Illustrated guide to recognize, prevent and manage phosphorus deficiency in maize.','Picture guide for know, prevent and manage phosphorus deficiency in maize.',4,'crop-maize',1,0,'{"symptoms":["Carence en phosphore du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,3),
('guide-04','fall-armyworm-maize','maize','pest','Chenille légionnaire du maïs','Fall armyworm in maize','Fall armyworm in maize','Fiche illustrée pour reconnaître, prévenir et gérer : chenille légionnaire du maïs.','Illustrated guide to recognize, prevent and manage fall armyworm in maize.','Picture guide for know, prevent and manage fall armyworm in maize.',4,'crop-maize',1,0,'{"symptoms":["Chenille légionnaire du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,4),
('guide-05','maize-streak','maize','disease','Striure du maïs','Maize streak disease','Maize streak disease','Fiche illustrée pour reconnaître, prévenir et gérer : striure du maïs.','Illustrated guide to recognize, prevent and manage maize streak disease.','Picture guide for know, prevent and manage maize streak disease.',4,'crop-maize',0,0,'{"symptoms":["Striure du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,5),
('guide-06','maize-rust','maize','disease','Rouille du maïs','Maize rust','Maize rust','Fiche illustrée pour reconnaître, prévenir et gérer : rouille du maïs.','Illustrated guide to recognize, prevent and manage maize rust.','Picture guide for know, prevent and manage maize rust.',4,'crop-maize',0,0,'{"symptoms":["Rouille du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,6),
('guide-07','stem-borer-maize','maize','pest','Foreurs de tiges du maïs','Maize stem borers','Maize stem borers','Fiche illustrée pour reconnaître, prévenir et gérer : foreurs de tiges du maïs.','Illustrated guide to recognize, prevent and manage maize stem borers.','Picture guide for know, prevent and manage maize stem borers.',4,'crop-maize',0,0,'{"symptoms":["Foreurs de tiges du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,7),
('guide-08','planting-maize','maize','practice','Bien semer le maïs','How to plant maize','How to plant maize','Fiche illustrée pour reconnaître, prévenir et gérer : bien semer le maïs.','Illustrated guide to recognize, prevent and manage how to plant maize.','Picture guide for know, prevent and manage how to plant maize.',4,'crop-maize',0,0,'{"symptoms":["Bien semer le maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,8),
('guide-09','weeding-maize','maize','practice','Désherbage du maïs','Maize weeding','Maize weeding','Fiche illustrée pour reconnaître, prévenir et gérer : désherbage du maïs.','Illustrated guide to recognize, prevent and manage maize weeding.','Picture guide for know, prevent and manage maize weeding.',4,'crop-maize',0,0,'{"symptoms":["Désherbage du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,9),
('guide-10','fertilizing-maize','maize','practice','Fertilisation raisonnée du maïs','Responsible maize fertilization','Responsible maize fertilization','Fiche illustrée pour reconnaître, prévenir et gérer : fertilisation raisonnée du maïs.','Illustrated guide to recognize, prevent and manage responsible maize fertilization.','Picture guide for know, prevent and manage responsible maize fertilization.',4,'crop-maize',0,0,'{"symptoms":["Fertilisation raisonnée du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,10),
('guide-11','harvest-maize','maize','practice','Récolte et séchage du maïs','Maize harvesting and drying','Maize harvesting and drying','Fiche illustrée pour reconnaître, prévenir et gérer : récolte et séchage du maïs.','Illustrated guide to recognize, prevent and manage maize harvesting and drying.','Picture guide for know, prevent and manage maize harvesting and drying.',4,'crop-maize',0,0,'{"symptoms":["Récolte et séchage du maïs"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,11),
('guide-12','storage-maize','maize','practice','Conserver le maïs sans pertes','Safe maize storage','Safe maize storage','Fiche illustrée pour reconnaître, prévenir et gérer : conserver le maïs sans pertes.','Illustrated guide to recognize, prevent and manage safe maize storage.','Picture guide for know, prevent and manage safe maize storage.',4,'crop-maize',0,0,'{"symptoms":["Conserver le maïs sans pertes"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,12),
('guide-13','cassava-mosaic','cassava','disease','Mosaïque du manioc','Cassava mosaic disease','Cassava mosaic disease','Fiche illustrée pour reconnaître, prévenir et gérer : mosaïque du manioc.','Illustrated guide to recognize, prevent and manage cassava mosaic disease.','Picture guide for know, prevent and manage cassava mosaic disease.',4,'crop-cassava',0,0,'{"symptoms":["Mosaïque du manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,13),
('guide-14','cassava-brown-streak','cassava','disease','Striure brune du manioc','Cassava brown streak disease','Cassava brown streak disease','Fiche illustrée pour reconnaître, prévenir et gérer : striure brune du manioc.','Illustrated guide to recognize, prevent and manage cassava brown streak disease.','Picture guide for know, prevent and manage cassava brown streak disease.',4,'crop-cassava',0,0,'{"symptoms":["Striure brune du manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,14),
('guide-15','cassava-bacterial-blight','cassava','disease','Bactériose du manioc','Cassava bacterial blight','Cassava bacterial blight','Fiche illustrée pour reconnaître, prévenir et gérer : bactériose du manioc.','Illustrated guide to recognize, prevent and manage cassava bacterial blight.','Picture guide for know, prevent and manage cassava bacterial blight.',4,'crop-cassava',0,0,'{"symptoms":["Bactériose du manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,15),
('guide-16','cassava-mealybug','cassava','pest','Cochenille farineuse du manioc','Cassava mealybug','Cassava mealybug','Fiche illustrée pour reconnaître, prévenir et gérer : cochenille farineuse du manioc.','Illustrated guide to recognize, prevent and manage cassava mealybug.','Picture guide for know, prevent and manage cassava mealybug.',4,'crop-cassava',0,0,'{"symptoms":["Cochenille farineuse du manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,16),
('guide-17','cassava-whitefly','cassava','pest','Aleurodes du manioc','Whiteflies on cassava','Whiteflies on cassava','Fiche illustrée pour reconnaître, prévenir et gérer : aleurodes du manioc.','Illustrated guide to recognize, prevent and manage whiteflies on cassava.','Picture guide for know, prevent and manage whiteflies on cassava.',4,'crop-cassava',0,0,'{"symptoms":["Aleurodes du manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,17),
('guide-18','cassava-root-rot','cassava','disease','Pourriture des racines du manioc','Cassava root rot','Cassava root rot','Fiche illustrée pour reconnaître, prévenir et gérer : pourriture des racines du manioc.','Illustrated guide to recognize, prevent and manage cassava root rot.','Picture guide for know, prevent and manage cassava root rot.',4,'crop-cassava',0,0,'{"symptoms":["Pourriture des racines du manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,18),
('guide-19','planting-cassava','cassava','practice','Choisir et planter les boutures','Selecting and planting cassava cuttings','Selecting and planting cassava cuttings','Fiche illustrée pour reconnaître, prévenir et gérer : choisir et planter les boutures.','Illustrated guide to recognize, prevent and manage selecting and planting cassava cuttings.','Picture guide for know, prevent and manage selecting and planting cassava cuttings.',4,'crop-cassava',0,0,'{"symptoms":["Choisir et planter les boutures"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,19),
('guide-20','soil-cassava','cassava','practice','Préparer le sol pour le manioc','Preparing soil for cassava','Preparing soil for cassava','Fiche illustrée pour reconnaître, prévenir et gérer : préparer le sol pour le manioc.','Illustrated guide to recognize, prevent and manage preparing soil for cassava.','Picture guide for know, prevent and manage preparing soil for cassava.',4,'crop-cassava',0,0,'{"symptoms":["Préparer le sol pour le manioc"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,20),
('guide-21','harvest-cassava','cassava','practice','Récolter le manioc au bon moment','Harvesting cassava at the right time','Harvesting cassava at the right time','Fiche illustrée pour reconnaître, prévenir et gérer : récolter le manioc au bon moment.','Illustrated guide to recognize, prevent and manage harvesting cassava at the right time.','Picture guide for know, prevent and manage harvesting cassava at the right time.',4,'crop-cassava',0,0,'{"symptoms":["Récolter le manioc au bon moment"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,21),
('guide-22','tomato-late-blight','tomato','disease','Mildiou de la tomate','Tomato late blight','Tomato late blight','Fiche illustrée pour reconnaître, prévenir et gérer : mildiou de la tomate.','Illustrated guide to recognize, prevent and manage tomato late blight.','Picture guide for know, prevent and manage tomato late blight.',4,'crop-tomato',0,0,'{"symptoms":["Mildiou de la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,22),
('guide-23','tomato-early-blight','tomato','disease','Alternariose de la tomate','Tomato early blight','Tomato early blight','Fiche illustrée pour reconnaître, prévenir et gérer : alternariose de la tomate.','Illustrated guide to recognize, prevent and manage tomato early blight.','Picture guide for know, prevent and manage tomato early blight.',4,'crop-tomato',0,0,'{"symptoms":["Alternariose de la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,23),
('guide-24','tomato-bacterial-wilt','tomato','disease','Flétrissement bactérien de la tomate','Tomato bacterial wilt','Tomato bacterial wilt','Fiche illustrée pour reconnaître, prévenir et gérer : flétrissement bactérien de la tomate.','Illustrated guide to recognize, prevent and manage tomato bacterial wilt.','Picture guide for know, prevent and manage tomato bacterial wilt.',4,'crop-tomato',0,0,'{"symptoms":["Flétrissement bactérien de la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,24),
('guide-25','tomato-leaf-curl','tomato','disease','Enroulement jaune des feuilles','Tomato yellow leaf curl','Tomato yellow leaf curl','Fiche illustrée pour reconnaître, prévenir et gérer : enroulement jaune des feuilles.','Illustrated guide to recognize, prevent and manage tomato yellow leaf curl.','Picture guide for know, prevent and manage tomato yellow leaf curl.',4,'crop-tomato',0,0,'{"symptoms":["Enroulement jaune des feuilles"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,25),
('guide-26','tomato-blossom-rot','tomato','deficiency','Nécrose apicale des fruits','Tomato blossom-end rot','Tomato blossom-end rot','Fiche illustrée pour reconnaître, prévenir et gérer : nécrose apicale des fruits.','Illustrated guide to recognize, prevent and manage tomato blossom-end rot.','Picture guide for know, prevent and manage tomato blossom-end rot.',4,'crop-tomato',0,0,'{"symptoms":["Nécrose apicale des fruits"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,26),
('guide-27','tomato-whitefly','tomato','pest','Aleurodes de la tomate','Whiteflies on tomato','Whiteflies on tomato','Fiche illustrée pour reconnaître, prévenir et gérer : aleurodes de la tomate.','Illustrated guide to recognize, prevent and manage whiteflies on tomato.','Picture guide for know, prevent and manage whiteflies on tomato.',4,'crop-tomato',0,0,'{"symptoms":["Aleurodes de la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,27),
('guide-28','tomato-fruitworm','tomato','pest','Noctuelle des fruits de tomate','Tomato fruitworm','Tomato fruitworm','Fiche illustrée pour reconnaître, prévenir et gérer : noctuelle des fruits de tomate.','Illustrated guide to recognize, prevent and manage tomato fruitworm.','Picture guide for know, prevent and manage tomato fruitworm.',4,'crop-tomato',0,0,'{"symptoms":["Noctuelle des fruits de tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,28),
('guide-29','nursery-tomato','tomato','practice','Réussir une pépinière de tomate','Successful tomato nursery','Successful tomato nursery','Fiche illustrée pour reconnaître, prévenir et gérer : réussir une pépinière de tomate.','Illustrated guide to recognize, prevent and manage successful tomato nursery.','Picture guide for know, prevent and manage successful tomato nursery.',4,'crop-tomato',0,0,'{"symptoms":["Réussir une pépinière de tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,29),
('guide-30','watering-tomato','tomato','practice','Bien arroser la tomate','Watering tomatoes correctly','Watering tomatoes correctly','Fiche illustrée pour reconnaître, prévenir et gérer : bien arroser la tomate.','Illustrated guide to recognize, prevent and manage watering tomatoes correctly.','Picture guide for know, prevent and manage watering tomatoes correctly.',4,'crop-tomato',0,0,'{"symptoms":["Bien arroser la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,30),
('guide-31','staking-tomato','tomato','practice','Tuteurer et tailler la tomate','Staking and pruning tomatoes','Staking and pruning tomatoes','Fiche illustrée pour reconnaître, prévenir et gérer : tuteurer et tailler la tomate.','Illustrated guide to recognize, prevent and manage staking and pruning tomatoes.','Picture guide for know, prevent and manage staking and pruning tomatoes.',4,'crop-tomato',0,0,'{"symptoms":["Tuteurer et tailler la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,31),
('guide-32','harvest-tomato','tomato','practice','Récolter et conserver la tomate','Harvesting and storing tomatoes','Harvesting and storing tomatoes','Fiche illustrée pour reconnaître, prévenir et gérer : récolter et conserver la tomate.','Illustrated guide to recognize, prevent and manage harvesting and storing tomatoes.','Picture guide for know, prevent and manage harvesting and storing tomatoes.',4,'crop-tomato',0,0,'{"symptoms":["Récolter et conserver la tomate"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,32),
('guide-33','peanut-leaf-spot','peanut','disease','Cercosporiose de l’arachide','Peanut leaf spot','Peanut leaf spot','Fiche illustrée pour reconnaître, prévenir et gérer : cercosporiose de l’arachide.','Illustrated guide to recognize, prevent and manage peanut leaf spot.','Picture guide for know, prevent and manage peanut leaf spot.',4,'crop-peanut',0,0,'{"symptoms":["Cercosporiose de l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,33),
('guide-34','peanut-rust','peanut','disease','Rouille de l’arachide','Peanut rust','Peanut rust','Fiche illustrée pour reconnaître, prévenir et gérer : rouille de l’arachide.','Illustrated guide to recognize, prevent and manage peanut rust.','Picture guide for know, prevent and manage peanut rust.',4,'crop-peanut',0,0,'{"symptoms":["Rouille de l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,34),
('guide-35','peanut-rosette','peanut','disease','Rosette de l’arachide','Peanut rosette disease','Peanut rosette disease','Fiche illustrée pour reconnaître, prévenir et gérer : rosette de l’arachide.','Illustrated guide to recognize, prevent and manage peanut rosette disease.','Picture guide for know, prevent and manage peanut rosette disease.',4,'crop-peanut',0,0,'{"symptoms":["Rosette de l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,35),
('guide-36','peanut-aphids','peanut','pest','Pucerons de l’arachide','Aphids on peanut','Aphids on peanut','Fiche illustrée pour reconnaître, prévenir et gérer : pucerons de l’arachide.','Illustrated guide to recognize, prevent and manage aphids on peanut.','Picture guide for know, prevent and manage aphids on peanut.',4,'crop-peanut',0,0,'{"symptoms":["Pucerons de l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,36),
('guide-37','planting-peanut','peanut','practice','Bien semer l’arachide','How to plant peanut','How to plant peanut','Fiche illustrée pour reconnaître, prévenir et gérer : bien semer l’arachide.','Illustrated guide to recognize, prevent and manage how to plant peanut.','Picture guide for know, prevent and manage how to plant peanut.',4,'crop-peanut',0,0,'{"symptoms":["Bien semer l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,37),
('guide-38','harvest-peanut','peanut','practice','Récolte de l’arachide','Peanut harvesting','Peanut harvesting','Fiche illustrée pour reconnaître, prévenir et gérer : récolte de l’arachide.','Illustrated guide to recognize, prevent and manage peanut harvesting.','Picture guide for know, prevent and manage peanut harvesting.',4,'crop-peanut',0,0,'{"symptoms":["Récolte de l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,38),
('guide-39','storage-peanut','peanut','practice','Séchage et stockage de l’arachide','Peanut drying and storage','Peanut drying and storage','Fiche illustrée pour reconnaître, prévenir et gérer : séchage et stockage de l’arachide.','Illustrated guide to recognize, prevent and manage peanut drying and storage.','Picture guide for know, prevent and manage peanut drying and storage.',4,'crop-peanut',0,0,'{"symptoms":["Séchage et stockage de l’arachide"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,39),
('guide-40','yellow-leaves','general','guide','Jaunissement des feuilles : causes fréquentes','Yellow leaves: common causes','Yellow leaves: common causes','Fiche illustrée pour reconnaître, prévenir et gérer : jaunissement des feuilles : causes fréquentes.','Illustrated guide to recognize, prevent and manage yellow leaves: common causes.','Picture guide for know, prevent and manage yellow leaves: common causes.',4,'library-hero',0,1,'{"symptoms":["Jaunissement des feuilles : causes fréquentes"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,40),
('guide-41','soil-moisture','general','guide','Reconnaître un stress hydrique','Recognizing water stress','Recognizing water stress','Fiche illustrée pour reconnaître, prévenir et gérer : reconnaître un stress hydrique.','Illustrated guide to recognize, prevent and manage recognizing water stress.','Picture guide for know, prevent and manage recognizing water stress.',4,'library-hero',0,0,'{"symptoms":["Reconnaître un stress hydrique"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,41),
('guide-42','ask-adviser','general','guide','Quand demander l’avis d’un conseiller ?','When to ask an adviser','When to ask an adviser','Fiche illustrée pour reconnaître, prévenir et gérer : quand demander l’avis d’un conseiller ?.','Illustrated guide to recognize, prevent and manage when to ask an adviser.','Picture guide for know, prevent and manage when to ask an adviser.',4,'library-hero',0,1,'{"symptoms":["Quand demander l’avis d’un conseiller ?"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,42),
('guide-43','safe-pesticides','general','practice','Utiliser les pesticides avec prudence','Using pesticides safely','Using pesticides safely','Fiche illustrée pour reconnaître, prévenir et gérer : utiliser les pesticides avec prudence.','Illustrated guide to recognize, prevent and manage using pesticides safely.','Picture guide for know, prevent and manage using pesticides safely.',4,'library-hero',0,0,'{"symptoms":["Utiliser les pesticides avec prudence"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,43),
('guide-44','compost','general','practice','Fabriquer et utiliser du compost','Making and using compost','Making and using compost','Fiche illustrée pour reconnaître, prévenir et gérer : fabriquer et utiliser du compost.','Illustrated guide to recognize, prevent and manage making and using compost.','Picture guide for know, prevent and manage making and using compost.',4,'library-hero',0,0,'{"symptoms":["Fabriquer et utiliser du compost"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,44),
('guide-45','crop-rotation','general','practice','Pratiquer la rotation des cultures','Crop rotation','Crop rotation','Fiche illustrée pour reconnaître, prévenir et gérer : pratiquer la rotation des cultures.','Illustrated guide to recognize, prevent and manage crop rotation.','Picture guide for know, prevent and manage crop rotation.',4,'library-hero',0,0,'{"symptoms":["Pratiquer la rotation des cultures"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,45),
('guide-46','field-observation','general','guide','Bien observer une parcelle malade','Observing a sick field','Observing a sick field','Fiche illustrée pour reconnaître, prévenir et gérer : bien observer une parcelle malade.','Illustrated guide to recognize, prevent and manage observing a sick field.','Picture guide for know, prevent and manage observing a sick field.',4,'library-hero',0,0,'{"symptoms":["Bien observer une parcelle malade"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,46),
('guide-47','soil-sampling','general','guide','Prélever un échantillon de sol','Taking a soil sample','Taking a soil sample','Fiche illustrée pour reconnaître, prévenir et gérer : prélever un échantillon de sol.','Illustrated guide to recognize, prevent and manage taking a soil sample.','Picture guide for know, prevent and manage taking a soil sample.',4,'library-hero',0,0,'{"symptoms":["Prélever un échantillon de sol"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,47),
('guide-48','farm-records','general','guide','Tenir un carnet de suivi agricole','Keeping farm records','Keeping farm records','Fiche illustrée pour reconnaître, prévenir et gérer : tenir un carnet de suivi agricole.','Illustrated guide to recognize, prevent and manage keeping farm records.','Picture guide for know, prevent and manage keeping farm records.',4,'library-hero',0,0,'{"symptoms":["Tenir un carnet de suivi agricole"],"actions":["Observer plusieurs plants","Comparer avec des plants sains","Demander conseil si le problème progresse"],"prevention":["Surveiller régulièrement la parcelle"]}',1,48);
INSERT OR IGNORE INTO library_reading_progress(guide_id,progress) VALUES('guide-01',40);

-- Les fiches 33 à 41 remplacent l'ancien lot arachide par les neuf fiches plantain du MVP.
UPDATE library_guides SET slug='black-sigatoka-plantain',crop_id='plantain',category='disease',title_fr='Cercosporiose noire du plantain',title_en='Black Sigatoka of plantain',title_pcm='Black Sigatoka for plantain',summary_fr='Reconnaître les stries et taches noires qui réduisent la surface verte des feuilles.',summary_en='Recognize streaks and black lesions that reduce healthy leaf area.',summary_pcm='Know black line and spot wey dey spoil plantain leaf.',image_key='crop-plantain' WHERE id='guide-33';
UPDATE library_guides SET slug='banana-weevil-plantain',crop_id='plantain',category='pest',title_fr='Charançon noir du plantain',title_en='Banana weevil',title_pcm='Plantain weevil',summary_fr='Identifier les galeries du bulbe, le mauvais ancrage et les plants qui se couchent.',summary_en='Identify corm tunnels, weak anchorage and fallen plants.',summary_pcm='Check hole for corm and plant wey dey fall.',image_key='crop-plantain' WHERE id='guide-34';
UPDATE library_guides SET slug='nematodes-plantain',crop_id='plantain',category='pest',title_fr='Nématodes du plantain',title_en='Plantain nematodes',title_pcm='Plantain nematode',summary_fr='Repérer les racines abîmées, la faible croissance et la verse provoquées par les nématodes.',summary_en='Spot damaged roots, poor growth and lodging caused by nematodes.',summary_pcm='See bad root, small growth and plant wey fall.',image_key='crop-plantain' WHERE id='guide-35';
UPDATE library_guides SET slug='fusarium-wilt-plantain',crop_id='plantain',category='disease',title_fr='Fusariose du plantain',title_en='Fusarium wilt of plantain',title_pcm='Plantain Fusarium wilt',summary_fr='Reconnaître le jaunissement progressif et les colorations internes du pseudotronc.',summary_en='Recognize progressive yellowing and internal pseudostem discoloration.',summary_pcm='Know yellow leaf and colour inside pseudostem.',image_key='crop-plantain' WHERE id='guide-36';
UPDATE library_guides SET slug='bacterial-wilt-plantain',crop_id='plantain',category='disease',title_fr='Flétrissement bactérien du plantain',title_en='Bacterial wilt of plantain',title_pcm='Plantain bacterial wilt',summary_fr='Détecter rapidement le flétrissement, les écoulements et le mûrissement anormal des fruits.',summary_en='Detect wilting, ooze and abnormal fruit ripening early.',summary_pcm='See wilt, water for stem and fruit wey ripe bad.',image_key='crop-plantain' WHERE id='guide-37';
UPDATE library_guides SET slug='planting-plantain',crop_id='plantain',category='practice',title_fr='Bien installer une plantation de plantain',title_en='Establishing a plantain field',title_pcm='How for plant plantain farm',summary_fr='Choisir des rejets sains, préparer les trous et respecter un bon espacement.',summary_en='Choose healthy suckers, prepare holes and use suitable spacing.',summary_pcm='Choose fine sucker, prepare hole and space am well.',image_key='crop-plantain' WHERE id='guide-38';
UPDATE library_guides SET slug='desuckering-plantain',crop_id='plantain',category='practice',title_fr='Œilletonnage et entretien du plantain',title_en='Plantain desuckering and maintenance',title_pcm='Clean and manage plantain sucker',summary_fr='Organiser les rejets, enlever les feuilles sèches et maintenir une touffe productive.',summary_en='Manage suckers, remove dry leaves and maintain a productive mat.',summary_pcm='Arrange sucker, cut dry leaf and keep good plant.',image_key='crop-plantain' WHERE id='guide-39';
UPDATE library_guides SET slug='bunch-protection-plantain',crop_id='plantain',category='practice',title_fr='Protéger le régime de plantain',title_en='Protecting plantain bunches',title_pcm='Protect plantain bunch',summary_fr='Limiter les blessures, ravageurs et défauts des fruits pendant le remplissage du régime.',summary_en='Reduce injuries, pests and fruit defects during bunch filling.',summary_pcm='Protect bunch from wound and insect as fruit dey grow.',image_key='crop-plantain',recommended=0 WHERE id='guide-40';
UPDATE library_guides SET slug='harvest-plantain',crop_id='plantain',category='practice',title_fr='Récolter et conserver le plantain',title_en='Harvesting and storing plantain',title_pcm='Harvest and keep plantain',summary_fr='Reconnaître la maturité, couper sans blesser les fruits et réduire les pertes.',summary_en='Recognize maturity, cut without damaging fruits and reduce losses.',summary_pcm='Know ripe time, cut well and reduce loss.',image_key='crop-plantain' WHERE id='guide-41';
